server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
      base-url: http://localhost:9411
  rabbitmq:
    host: 115.231.156.236
    port: 5672
    username: guest
    password: guest

