server:
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user:
        name: admin
        password: 123456

management:
  security:
    enabled: false

spring:
  application:
    name: admin-server
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: turbine-service

security.basic.enabled: false
security:
  user:
    name: admin
    password: 123456

endpoints:
  health:
    sensitive: false
    enabled: true
  actuator:
    enabled: true
    sensitive: false
  beans:
    sensitive: false
    enabled: true

logging:
  file: "logs/boot-admin-sample.log"