server:
    port: 8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-monitor-client
#feign:
#  hystrix:
#    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
turbine:
  aggregator:
    clusterConfig: default
  appConfig: eureka-ribbon-client,eureka-feign
  clusterNameExpression: new String("default")