eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:
      path: /hiapi/*
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/*
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/*
      serviceId: erureka-feign-client